test gradle cache + other test report action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,21 +1,22 @@
-name: Build
+name: Build Bonita Community
 on:
   push:
     branches:
       - dev
   pull_request:
-    types: [opened, synchronize, reopened]
+    types: [ opened, synchronize, reopened ]
 jobs:
-  build:
-    name: Build
+  build-bonita-community:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - name: ↙️ Checkout project sources
+        uses: actions/checkout@v4
+      #        with:
+      #          sparse-checkout: '.'
       - name: Set up JDK 17
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v3
         with:
+          distribution: temurin
           java-version: 17
       - name: Cache SonarCloud packages
         uses: actions/cache@v1
@@ -23,22 +24,15 @@ jobs:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
-      - name: Cache Gradle packages
-        uses: actions/cache@v1
+      - name: 🔧 Setup Gradle
+        uses: gradle/gradle-build-action@v2
         with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-          restore-keys: ${{ runner.os }}-gradle
-      - name: Build and test
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#        run: ./gradlew build sonarqube -Dsonar.scanner.force-deprecated-java-version=true
-        run: ./gradlew test
-      - name: Report tests
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+          cache-read-only: false
+      - name: ⚙️ Run Community build & ✔️ unit tests
+        run: ./gradlew build
+      - name: 🚀 Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
         with:
-          name: JUnit Tests
-          path: '**/build/test-results/**/*.xml'    # Path to test results
-          reporter: java-junit        # Format of test results
+          report_paths: '**/build/test-results/**/*.xml'
+          detailed_summary: true
